Resources:
  CountriesDynamoDBTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: Countries
      BillingMode: PAY_PER_REQUEST
      Replicas:
        - us-east-1
        - us-west-2
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true